import { RawProject } from "./types";

export const FALLBACK_DATE = "17 Juni 2026";

export const DEFAULT_RAW_PROJECTS: RawProject[] = [
  {
    "Project Name": "Integrasi Core Banking API Gateway",
    "Ticket": "48201793",
    "Owner Name": "Dany Alparigi",
    "Owner Div": "BPD",
    "PIC Name": "Andik Prasetya",
    "PIC Short Name": "Andik",
    "Type Project": "Project Utama",
    "Last Status": "Dev On Progress",
    "Milestone": "OPEN",
    "Status PMA": "OPEN",
    "Prioritas Mgmt": "High",
    "Year": 2026,
    "Period": "Jan-26",
    "Kuartal": "Q1",
    "Durasi Project (IT)": "Jan–Jun 2026",
    "Project diajukan": "Q1 2026",
    "Created time": "January 14, 2026 10:00 AM",
    "Last edited time": "June 17, 2026 5:00 PM",
    "Final FPS Approved": "January 20, 2026",
    "Final FSD Start": "January 22, 2026",
    "Tgl FPS disetujui": "January 20, 2026",
    "Tgl upload From Feedback ke PMA": "January 21, 2026",
    "Tanggal Canceled": null,
    "Tanggal Input Caldev": null,
    "Tanggal Input Timeline": null,
    "(FSD) Elapse Days": "12",
    "(FSD) Late Days": "0 (Tepat Waktu)",
    "(FSD) Plan in Week": "W1-W3",
    "(FSD) Status": "Done",
    "FSD SLA": "Achieved",
    "FSD SLA YEAR": 2026,
    "(Dev) Elapse Days": "48",
    "(Dev) Late Days": "24 (Telat Berat >=15 Hari)",
    "(Dev) Plan in Week": "W4-W12",
    "(Dev) Status": "In Progress",
    "DEV SLA": "Not Achieved",
    "DEV SLA YEAR": 2026,
    "(SIT) Elapse Days": "0",
    "(SIT) Late Days": "0 (Tepat Waktu)",
    "(SIT) Status": "On Queue",
    "SIT SLA": "Without",
    "SIT SLA YEAR": null,
    "(UAT) Elapse Days": null,
    "(UAT) Late Days": null,
    "(UAT) Status": null,
    "UAT SLA": "Without",
    "UAT SLA YEAR": null,
    "(Live) Plan in Week": "W16",
    "(Live) Status": null,
    "Live SLA": "Without",
    "LIVE SLA YEAR": null,
    "Reschedule UAT": 0,
    "Rata-rata Nilai Feedback User : ": null,
    "Rata-rata Nilai Feedback User New :": 0,
    "Bobot Project ": "Big"
  },
  {
    "Project Name": "Enhancement Menu Pembatalan ATM CIT",
    "Ticket": "73920184",
    "Owner Name": "Rachmat Hidayat",
    "Owner Div": "COS",
    "PIC Name": "Ericko Lim",
    "PIC Short Name": "Ericko",
    "Type Project": "Enhance Kecil",
    "Last Status": "Change Request On Progress",
    "Milestone": "OPEN",
    "Status PMA": "OPEN",
    "Prioritas Mgmt": "Medium",
    "Year": 2026,
    "Period": "Jan-26",
    "Kuartal": "Q1",
    "Durasi Project (IT)": "Jan–Mei 2026",
    "Project diajukan": "Q1 2026",
    "Created time": "January 15, 2026 11:00 AM",
    "Last edited time": "June 17, 2026 5:00 PM",
    "Final FPS Approved": "January 18, 2026",
    "Final FSD Start": "January 20, 2026",
    "Tgl FPS disetujui": "January 18, 2026",
    "Tgl upload From Feedback ke PMA": "January 19, 2026",
    "Tanggal Canceled": null,
    "Tanggal Input Caldev": null,
    "Tanggal Input Timeline": null,
    "(FSD) Elapse Days": "4",
    "(FSD) Late Days": "0 (Tepat Waktu)",
    "(FSD) Status": "Done",
    "FSD SLA": "Achieved",
    "FSD SLA YEAR": 2026,
    "(Dev) Elapse Days": "18",
    "(Dev) Late Days": "2 (Telat Ringan 1-3 Hari)",
    "(Dev) Status": "Done",
    "DEV SLA": "Not Achieved",
    "DEV SLA YEAR": 2026,
    "(SIT) Elapse Days": "21",
    "(SIT) Late Days": "17 (Telat Berat >=15 Hari)",
    "(SIT) Status": "Done",
    "SIT SLA": "Not Achieved",
    "SIT SLA YEAR": 2026,
    "(UAT) Elapse Days": "6",
    "(UAT) Late Days": "0 (Tepat Waktu)",
    "(UAT) Status": "Done",
    "UAT SLA": "Achieved",
    "UAT SLA YEAR": 2026,
    "(Live) Plan in Week": "W14",
    "(Live) Status": "Change Request",
    "Live SLA": "Without",
    "LIVE SLA YEAR": null,
    "Reschedule UAT": 3,
    "Rata-rata Nilai Feedback User : ": null,
    "Rata-rata Nilai Feedback User New :": 0,
    "Bobot Project ": "Medium"
  },
  {
    "Project Name": "Pembuatan Custom Akses (Sentralisasi POC)",
    "Ticket": "10583926",
    "Owner Name": "Taufik Hidayat",
    "Owner Div": "IT",
    "PIC Name": "Faris Ramadhan",
    "PIC Short Name": "Faris",
    "Type Project": "Internal IT",
    "Last Status": "UAT On Progress",
    "Milestone": "OPEN",
    "Status PMA": "OPEN",
    "Prioritas Mgmt": "Medium",
    "Year": 2026,
    "Period": "Feb-26",
    "Kuartal": "Q1",
    "Durasi Project (IT)": "Feb–Jun 2026",
    "Project diajukan": "Q1 2026",
    "Created time": "February 01, 2026 9:00 AM",
    "Last edited time": "June 17, 2026 5:00 PM",
    "Final FPS Approved": "February 05, 2026",
    "Final FSD Start": "February 08, 2026",
    "Tgl FPS disetujui": "February 05, 2026",
    "Tgl upload From Feedback ke PMA": "February 06, 2026",
    "Tanggal Canceled": null,
    "Tanggal Input Caldev": null,
    "Tanggal Input Timeline": null,
    "(FSD) Elapse Days": "15",
    "(FSD) Late Days": "0 (Tepat Waktu)",
    "(FSD) Status": "Done",
    "FSD SLA": "Achieved",
    "FSD SLA YEAR": 2026,
    "(Dev) Elapse Days": "31",
    "(Dev) Late Days": "11 (Telat Sedang 4-14 Hari)",
    "(Dev) Status": "Done",
    "DEV SLA": "Not Achieved",
    "DEV SLA YEAR": 2026,
    "(SIT) Elapse Days": "5",
    "(SIT) Late Days": "2 (Telat Ringan 1-3 Hari)",
    "(SIT) Status": "Done",
    "SIT SLA": "Not Achieved",
    "SIT SLA YEAR": 2026,
    "(UAT) Elapse Days": "4",
    "(UAT) Late Days": "0 (Tepat Waktu)",
    "(UAT) Status": "In Progress",
    "UAT SLA": "Without",
    "UAT SLA YEAR": null,
    "(Live) Plan in Week": "W20",
    "(Live) Status": null,
    "Live SLA": "Without",
    "LIVE SLA YEAR": null,
    "Reschedule UAT": 1,
    "Rata-rata Nilai Feedback User : ": null,
    "Rata-rata Nilai Feedback User New :": 0,
    "Bobot Project ": "Small"
  },
  {
    "Project Name": "Dashboard Monitoring Kredit UMKM",
    "Ticket": "64719205",
    "Owner Name": "Lia Amalia",
    "Owner Div": "BPD",
    "PIC Name": "Faris Ramadhan",
    "PIC Short Name": "Faris",
    "Type Project": "Project Utama",
    "Last Status": "Dev On Progress",
    "Milestone": "OPEN",
    "Status PMA": "OPEN",
    "Prioritas Mgmt": "High",
    "Year": 2026,
    "Period": "Feb-26",
    "Kuartal": "Q1",
    "Durasi Project (IT)": "Feb–Jul 2026",
    "Project diajukan": "Q1 2026",
    "Created time": "February 10, 2026 4:00 PM",
    "Last edited time": "June 17, 2026 5:00 PM",
    "Final FPS Approved": "February 14, 2026",
    "Final FSD Start": "February 18, 2026",
    "Tgl FPS disetujui": "February 14, 2026",
    "Tgl upload From Feedback ke PMA": "February 15, 2026",
    "Tanggal Canceled": null,
    "Tanggal Input Caldev": null,
    "Tanggal Input Timeline": null,
    "(FSD) Elapse Days": "14",
    "(FSD) Late Days": "0 (Tepat Waktu)",
    "(FSD) Status": "Done",
    "FSD SLA": "Achieved",
    "FSD SLA YEAR": 2026,
    "(Dev) Elapse Days": "42",
    "(Dev) Late Days": "5 (Telat Sedang 4-14 Hari)",
    "(Dev) Status": "In Progress",
    "DEV SLA": "Not Achieved",
    "DEV SLA YEAR": 2026,
    "(SIT) Elapse Days": null,
    "(SIT) Late Days": null,
    "(SIT) Status": null,
    "SIT SLA": "Without",
    "SIT SLA YEAR": null,
    "(UAT) Elapse Days": null,
    "(UAT) Late Days": null,
    "(UAT) Status": null,
    "UAT SLA": "Without",
    "UAT SLA YEAR": null,
    "(Live) Plan in Week": "W24",
    "Reschedule UAT": 0,
    "Rata-rata Nilai Feedback User : ": null,
    "Rata-rata Nilai Feedback User New :": 0,
    "Bobot Project ": "Big"
  },
  {
    "Project Name": "Upgrade Infrastruktur VPN Kantor",
    "Ticket": "29384715",
    "Owner Name": "Taufik Hidayat",
    "Owner Div": "IT",
    "PIC Name": "Genta Buana",
    "PIC Short Name": "Genta",
    "Type Project": "Internal IT",
    "Last Status": "Hold By Owner",
    "Milestone": "OPEN",
    "Status PMA": "OPEN",
    "Prioritas Mgmt": "Medium",
    "Year": 2026,
    "Period": "Mar-26",
    "Kuartal": "Q1",
    "Durasi Project (IT)": "Mar–Agu 2026",
    "Project diajukan": "Q1 2026",
    "Created time": "March 02, 2026 8:00 AM",
    "Last edited time": "June 17, 2026 5:00 PM",
    "Final FPS Approved": "March 08, 2026",
    "Final FSD Start": "March 12, 2026",
    "Tgl FPS disetujui": "March 08, 2026",
    "Tgl upload From Feedback ke PMA": "March 10, 2026",
    "Tanggal Canceled": null,
    "Tanggal Input Caldev": null,
    "Tanggal Input Timeline": null,
    "(FSD) Elapse Days": "28",
    "(FSD) Late Days": "19 (Telat Berat >=15 Hari)",
    "(FSD) Status": "Done",
    "FSD SLA": "Not Achieved",
    "FSD SLA YEAR": 2026,
    "(Dev) Elapse Days": "12",
    "(Dev) Late Days": "0 (Tepat Waktu)",
    "(Dev) Status": "In Progress",
    "DEV SLA": "Without",
    "DEV SLA YEAR": null,
    "(SIT) Elapse Days": null,
    "(SIT) Late Days": null,
    "(SIT) Status": null,
    "SIT SLA": "Without",
    "SIT SLA YEAR": null,
    "Reschedule UAT": 0,
    "Rata-rata Nilai Feedback User : ": null,
    "Rata-rata Nilai Feedback User New :": 0,
    "Bobot Project ": "Medium"
  },
  {
    "Project Name": "Otomasi Rekonsiliasi Kartu Debit",
    "Ticket": "85016349",
    "Owner Name": "Susilo Bambang",
    "Owner Div": "Finance",
    "PIC Name": "Haris Setiadi",
    "PIC Short Name": "Haris",
    "Type Project": "Approval Digital",
    "Last Status": "Dev On Progress",
    "Milestone": "OPEN",
    "Status PMA": "OPEN",
    "Prioritas Mgmt": "Medium",
    "Year": 2026,
    "Period": "Mar-26",
    "Kuartal": "Q1",
    "Durasi Project (IT)": "Mar–Jul 2026",
    "Project diajukan": "Q1 2026",
    "Created time": "March 15, 2026 3:00 PM",
    "Last edited time": "June 17, 2026 5:00 PM",
    "Final FPS Approved": "March 20, 2026",
    "Final FSD Start": "March 24, 2026",
    "Tgl FPS disetujui": "March 20, 2026",
    "Tgl upload From Feedback ke PMA": "March 22, 2026",
    "Tanggal Canceled": null,
    "Tanggal Input Caldev": null,
    "Tanggal Input Timeline": null,
    "(FSD) Elapse Days": "11",
    "(FSD) Late Days": "0 (Tepat Waktu)",
    "(FSD) Status": "Done",
    "FSD SLA": "Achieved",
    "FSD SLA YEAR": 2026,
    "(Dev) Elapse Days": "34",
    "(Dev) Late Days": "7 (Telat Sedang 4-14 Hari)",
    "(Dev) Status": "In Progress",
    "DEV SLA": "Not Achieved",
    "DEV SLA YEAR": 2026,
    "Reschedule UAT": 0,
    "Rata-rata Nilai Feedback User : ": null,
    "Rata-rata Nilai Feedback User New :": 0,
    "Bobot Project ": "Medium"
  },
  {
    "Project Name": "Enhancement Approval Digital L2",
    "Ticket": "37250918",
    "Owner Name": "Susilo Bambang",
    "Owner Div": "Finance",
    "PIC Name": "Iwan Fals",
    "PIC Short Name": "Iwan",
    "Type Project": "Approval Digital",
    "Last Status": "FSD On Progress",
    "Milestone": "OPEN",
    "Status PMA": "OPEN",
    "Prioritas Mgmt": "Low",
    "Year": 2026,
    "Period": "Apr-26",
    "Kuartal": "Q2",
    "Durasi Project (IT)": "Apr–Agu 2026",
    "Project diajukan": "Q2 2026",
    "Created time": "April 05, 2026 10:00 AM",
    "Last edited time": "June 17, 2026 5:00 PM",
    "Final FPS Approved": "April 10, 2026",
    "Final FSD Start": "April 12, 2026",
    "Tgl FPS disetujui": "April 10, 2026",
    "Tgl upload From Feedback ke PMA": "April 11, 2026",
    "Tanggal Canceled": null,
    "Tanggal Input Caldev": null,
    "Tanggal Input Timeline": null,
    "(FSD) Elapse Days": "10",
    "(FSD) Late Days": "2 (Telat Ringan 1-3 Hari)",
    "(FSD) Status": "In Progress",
    "FSD SLA": "Not Achieved",
    "FSD SLA YEAR": 2026,
    "DEV SLA": "Without",
    "Reschedule UAT": 0,
    "Rata-rata Nilai Feedback User : ": null,
    "Rata-rata Nilai Feedback User New :": 0,
    "Bobot Project ": "Small"
  },
  {
    "Project Name": "Integrasi Dukcapil e-KTP Fase 2",
    "Ticket": "91648027",
    "Owner Name": "Dany Alparigi",
    "Owner Div": "BPD",
    "PIC Name": "Andik Prasetya",
    "PIC Short Name": "Andik",
    "Type Project": "Project Utama",
    "Last Status": "On Queue",
    "Milestone": "OPEN",
    "Status PMA": "OPEN",
    "Prioritas Mgmt": "High",
    "Year": 2026,
    "Period": "Mei-26",
    "Kuartal": "Q2",
    "Durasi Project (IT)": "Mei–Okt 2026",
    "Project diajukan": "Q2 2026",
    "Created time": "May 10, 2026 2:00 PM",
    "Last edited time": "June 17, 2026 5:00 PM",
    "Final FPS Approved": "May 15, 2026",
    "Final FSD Start": null,
    "Tgl FPS disetujui": "May 15, 2026",
    "Tgl upload From Feedback ke PMA": null,
    "Tanggal Canceled": null,
    "Tanggal Input Caldev": null,
    "Tanggal Input Timeline": null,
    "FSD SLA": "Without",
    "DEV SLA": "Without",
    "Reschedule UAT": 0,
    "Rata-rata Nilai Feedback User : ": null,
    "Rata-rata Nilai Feedback User New :": 0,
    "Bobot Project ": "Big"
  },
  {
    "Project Name": "Revamp Portal Internal Kepegawaian",
    "Ticket": "58273910",
    "Owner Name": "Hesty Purwanti",
    "Owner Div": "HR",
    "PIC Name": "Kurniawan Dwi",
    "PIC Short Name": "Kurniawan",
    "Type Project": "Internal IT",
    "Last Status": "On Queue",
    "Milestone": "OPEN",
    "Status PMA": "OPEN",
    "Prioritas Mgmt": "Medium",
    "Year": 2026,
    "Period": "Mei-26",
    "Kuartal": "Q2",
    "Durasi Project (IT)": "Mei–Nov 2026",
    "Project diajukan": "Q2 2026",
    "Created time": "May 12, 2026 11:00 AM",
    "Last edited time": "June 17, 2026 5:00 PM",
    "Final FPS Approved": "May 18, 2026",
    "Final FSD Start": null,
    "Tgl FPS disetujui": "May 18, 2026",
    "Tgl upload From Feedback ke PMA": null,
    "Tanggal Canceled": null,
    "Tanggal Input Caldev": null,
    "Tanggal Input Timeline": null,
    "FSD SLA": "Without",
    "DEV SLA": "Without",
    "Reschedule UAT": 0,
    "Rata-rata Nilai Feedback User : ": null,
    "Rata-rata Nilai Feedback User New :": 0,
    "Bobot Project ": "Medium"
  },
  {
    "Project Name": "Enhancement Limit Transaksi QRIS",
    "Ticket": "40619285",
    "Owner Name": "Rachmat Hidayat",
    "Owner Div": "COS",
    "PIC Name": "Lutfi Hakim",
    "PIC Short Name": "Lutfi",
    "Type Project": "Enhance Kecil",
    "Last Status": "On Queue",
    "Milestone": "OPEN",
    "Status PMA": "OPEN",
    "Prioritas Mgmt": "High",
    "Year": 2026,
    "Period": "Jun-26",
    "Kuartal": "Q2",
    "Durasi Project (IT)": "Jun–Sep 2026",
    "Project diajukan": "Q2 2026",
    "Created time": "June 05, 2026 9:00 AM",
    "Last edited time": "June 17, 2026 5:00 PM",
    "Final FPS Approved": "June 10, 2026",
    "Final FSD Start": null,
    "Tgl FPS disetujui": "June 10, 2026",
    "Tgl upload From Feedback ke PMA": null,
    "Tanggal Canceled": null,
    "Tanggal Input Caldev": null,
    "Tanggal Input Timeline": null,
    "FSD SLA": "Without",
    "DEV SLA": "Without",
    "Reschedule UAT": 0,
    "Rata-rata Nilai Feedback User : ": null,
    "Rata-rata Nilai Feedback User New :": 0,
    "Bobot Project ": "Small"
  },
  {
    "Project Name": "FPS Penyesuaian Web Karir V3",
    "Ticket": "76130498",
    "Owner Name": "Hesty Purwanti",
    "Owner Div": "HR",
    "PIC Name": "Marta Dinata",
    "PIC Short Name": "Marta",
    "Type Project": "Internal IT",
    "Last Status": "FPS",
    "Milestone": "OPEN",
    "Status PMA": "OPEN",
    "Prioritas Mgmt": "Low",
    "Year": 2026,
    "Period": "Jun-26",
    "Kuartal": "Q2",
    "Durasi Project (IT)": "Jun–Sep 2026",
    "Project diajukan": "Q2 2026",
    "Created time": "June 12, 2026 10:00 AM",
    "Last edited time": "June 17, 2026 5:00 PM",
    "Final FPS Approved": "June 15, 2026",
    "Final FSD Start": null,
    "Tgl FPS disetujui": "June 15, 2026",
    "Tgl upload From Feedback ke PMA": null,
    "Tanggal Canceled": null,
    "Tanggal Input Caldev": null,
    "Tanggal Input Timeline": null,
    "FSD SLA": "Without",
    "DEV SLA": "Without",
    "Reschedule UAT": 0,
    "Rata-rata Nilai Feedback User : ": null,
    "Rata-rata Nilai Feedback User New :": 0,
    "Bobot Project ": "Small"
  },
  {
    "Project Name": "Migrasi Database Treasury",
    "Ticket": "13947602",
    "Owner Name": "Susilo Bambang",
    "Owner Div": "Finance",
    "PIC Name": "Nando Pratama",
    "PIC Short Name": "Nando",
    "Type Project": "Project Utama",
    "Last Status": "Live On Monitoring",
    "Milestone": "CLOSED",
    "Status PMA": "CLOSED",
    "Prioritas Mgmt": "High",
    "Year": 2025,
    "Period": "Feb-25",
    "Kuartal": "Q1",
    "Durasi Project (IT)": "Feb–Jun 2025",
    "Project diajukan": "Q1 2025",
    "Created time": "February 12, 2025 8:00 AM",
    "Last edited time": "June 17, 2026 5:00 PM",
    "Final FPS Approved": "February 18, 2025",
    "Final FSD Start": "February 22, 2025",
    "Tgl FPS disetujui": "February 18, 2025",
    "Tgl upload From Feedback ke PMA": "February 20, 2025",
    "Tanggal Canceled": null,
    "Tanggal Input Caldev": null,
    "Tanggal Input Timeline": null,
    "(FSD) Elapse Days": "14",
    "(FSD) Late Days": "0 (Tepat Waktu)",
    "(FSD) Status": "Done",
    "FSD SLA": "Achieved",
    "FSD SLA YEAR": 2025,
    "(Dev) Elapse Days": "62",
    "(Dev) Late Days": "21 (Telat Berat >=15 Hari)",
    "(Dev) Status": "Done",
    "DEV SLA": "Not Achieved",
    "DEV SLA YEAR": 2025,
    "(SIT) Elapse Days": "8",
    "(SIT) Late Days": "0 (Tepat Waktu)",
    "(SIT) Status": "Done",
    "SIT SLA": "Achieved",
    "SIT SLA YEAR": 2025,
    "(UAT) Elapse Days": "18",
    "(UAT) Late Days": "3 (Telat Ringan 1-3 Hari)",
    "(UAT) Status": "Done",
    "UAT SLA": "Not Achieved",
    "UAT SLA YEAR": 2025,
    "(Live) Plan in Week": "W16",
    "(Live) Status": "Done",
    "(Live) Realized in date": "June 12, 2025",
    "Live SLA": "Achieved",
    "LIVE SLA YEAR": 2025,
    "Reschedule UAT": 1,
    "Rata-rata Nilai Feedback User : ": 3.67,
    "Rata-rata Nilai Feedback User New :": 3.67,
    "Bobot Project ": "Big"
  },
  {
    "Project Name": "Otomasi Laporan Regulatori OJK",
    "Ticket": "60285417",
    "Owner Name": "Rian Andriana",
    "Owner Div": "Risk Mgmt",
    "PIC Name": "Oscar Sandino",
    "PIC Short Name": "Oscar",
    "Type Project": "Project Utama",
    "Last Status": "Live On Monitoring",
    "Milestone": "CLOSED",
    "Status PMA": "CLOSED",
    "Prioritas Mgmt": "High",
    "Year": 2025,
    "Period": "Mar-25",
    "Kuartal": "Q1",
    "Durasi Project (IT)": "Mar–Agu 2025",
    "Project diajukan": "Q1 2025",
    "Created time": "March 05, 2025 10:00 AM",
    "Last edited time": "June 17, 2026 5:00 PM",
    "Final FPS Approved": "March 10, 2025",
    "Final FSD Start": "March 14, 2025",
    "Tgl FPS disetujui": "March 10, 2025",
    "Tgl upload From Feedback ke PMA": "March 12, 2025",
    "Tanggal Canceled": null,
    "Tanggal Input Caldev": null,
    "Tanggal Input Timeline": null,
    "(FSD) Elapse Days": "12",
    "(FSD) Late Days": "0 (Tepat Waktu)",
    "(FSD) Status": "Done",
    "FSD SLA": "Achieved",
    "FSD SLA YEAR": 2025,
    "(Dev) Elapse Days": "45",
    "(Dev) Late Days": "9 (Telat Sedang 4-14 Hari)",
    "(Dev) Status": "Done",
    "DEV SLA": "Not Achieved",
    "DEV SLA YEAR": 2025,
    "(SIT) Elapse Days": "12",
    "(SIT) Late Days": "2 (Telat Ringan 1-3 Hari)",
    "(SIT) Status": "Done",
    "SIT SLA": "Not Achieved",
    "SIT SLA YEAR": 2025,
    "(UAT) Elapse Days": "15",
    "(UAT) Late Days": "0 (Tepat Waktu)",
    "(UAT) Status": "Done",
    "UAT SLA": "Achieved",
    "UAT SLA YEAR": 2025,
    "(Live) Realized in date": "August 15, 2025",
    "Live SLA": "Achieved",
    "LIVE SLA YEAR": 2025,
    "Reschedule UAT": 2,
    "Rata-rata Nilai Feedback User : ": 4.0,
    "Rata-rata Nilai Feedback User New :": 4.0,
    "Bobot Project ": "Big"
  },
  {
    "Project Name": "Revamp Mobile Banking Dashboard",
    "Ticket": "84019356",
    "Owner Name": "Dany Alparigi",
    "Owner Div": "BPD",
    "PIC Name": "Putra Mandiri",
    "PIC Short Name": "Putra",
    "Type Project": "Project Utama",
    "Last Status": "Live On Monitoring",
    "Milestone": "CLOSED",
    "Status PMA": "CLOSED",
    "Prioritas Mgmt": "High",
    "Year": 2025,
    "Period": "Apr-25",
    "Kuartal": "Q2",
    "Durasi Project (IT)": "Apr–Sep 2025",
    "Project diajukan": "Q2 2025",
    "Created time": "April 10, 2025 9:00 AM",
    "Last edited time": "June 17, 2026 5:00 PM",
    "Final FPS Approved": "April 15, 2025",
    "Final FSD Start": "April 18, 2025",
    "Tgl FPS disetujui": "April 15, 2025",
    "Tgl upload From Feedback ke PMA": "April 16, 2025",
    "Tanggal Canceled": null,
    "Tanggal Input Caldev": null,
    "Tanggal Input Timeline": null,
    "(FSD) Elapse Days": "10",
    "(FSD) Late Days": "0 (Tepat Waktu)",
    "(FSD) Status": "Done",
    "FSD SLA": "Achieved",
    "FSD SLA YEAR": 2025,
    "(Dev) Elapse Days": "31",
    "(Dev) Late Days": "0 (Tepat Waktu)",
    "(Dev) Status": "Done",
    "DEV SLA": "Achieved",
    "DEV SLA YEAR": 2025,
    "(SIT) Elapse Days": "24",
    "(SIT) Late Days": "12 (Telat Sedang 4-14 Hari)",
    "(SIT) Status": "Done",
    "SIT SLA": "Not Achieved",
    "SIT SLA YEAR": 2025,
    "(UAT) Elapse Days": "19",
    "(UAT) Late Days": "4 (Telat Sedang 4-14 Hari)",
    "(UAT) Status": "Done",
    "UAT SLA": "Not Achieved",
    "UAT SLA YEAR": 2025,
    "(Live) Realized in date": "September 20, 2025",
    "Live SLA": "Achieved",
    "LIVE SLA YEAR": 2025,
    "Reschedule UAT": 1,
    "Rata-rata Nilai Feedback User : ": 4.25,
    "Rata-rata Nilai Feedback User New :": 4.25,
    "Bobot Project ": "Big"
  },
  {
    "Project Name": "Enhancement e-KYC Verification",
    "Ticket": "25738094",
    "Owner Name": "Rachmat Hidayat",
    "Owner Div": "COS",
    "PIC Name": "Qomaruddin",
    "PIC Short Name": "Qomar",
    "Type Project": "Enhance Kecil",
    "Last Status": "Live On Monitoring",
    "Milestone": "CLOSED",
    "Status PMA": "CLOSED",
    "Prioritas Mgmt": "Medium",
    "Year": 2025,
    "Period": "Mei-25",
    "Kuartal": "Q2",
    "Durasi Project (IT)": "Mei–Okt 2025",
    "Project diajukan": "Q2 2025",
    "Created time": "May 08, 2025 3:00 PM",
    "Last edited time": "June 17, 2026 5:00 PM",
    "Final FPS Approved": "May 14, 2025",
    "Final FSD Start": "May 18, 2025",
    "Tgl FPS disetujui": "May 14, 2025",
    "Tgl upload From Feedback ke PMA": "May 15, 2025",
    "Tanggal Canceled": null,
    "Tanggal Input Caldev": null,
    "Tanggal Input Timeline": null,
    "(FSD) Elapse Days": "12",
    "(FSD) Late Days": "2 (Telat Ringan 1-3 Hari)",
    "(FSD) Status": "Done",
    "FSD SLA": "Not Achieved",
    "FSD SLA YEAR": 2025,
    "(Dev) Elapse Days": "21",
    "(Dev) Late Days": "2 (Telat Ringan 1-3 Hari)",
    "(Dev) Status": "Done",
    "DEV SLA": "Not Achieved",
    "DEV SLA YEAR": 2025,
    "(SIT) Elapse Days": "5",
    "(SIT) Late Days": "0 (Tepat Waktu)",
    "(SIT) Status": "Done",
    "SIT SLA": "Achieved",
    "SIT SLA YEAR": 2025,
    "(UAT) Elapse Days": "18",
    "(UAT) Late Days": "6 (Telat Sedang 4-14 Hari)",
    "(UAT) Status": "Done",
    "UAT SLA": "Not Achieved",
    "UAT SLA YEAR": 2025,
    "(Live) Realized in date": "October 12, 2025",
    "Live SLA": "Achieved",
    "LIVE SLA YEAR": 2025,
    "Reschedule UAT": 2,
    "Rata-rata Nilai Feedback User : ": null,
    "Rata-rata Nilai Feedback User New :": 0,
    "Bobot Project ": "Small"
  },
  {
    "Project Name": "Penambahan Fitur Notifikasi Push",
    "Ticket": "97412063",
    "Owner Name": "Sinta Bella",
    "Owner Div": "Marketing",
    "PIC Name": "Rahmat Kartolo",
    "PIC Short Name": "Rahmat",
    "Type Project": "Enhance Kecil",
    "Last Status": "Live On Monitoring",
    "Milestone": "CLOSED",
    "Status PMA": "CLOSED",
    "Prioritas Mgmt": "Low",
    "Year": 2025,
    "Period": "Jun-25",
    "Kuartal": "Q2",
    "Durasi Project (IT)": "Jun–Nov 2025",
    "Project diajukan": "Q2 2025",
    "Created time": "June 11, 2025 1:00 PM",
    "Last edited time": "June 17, 2026 5:00 PM",
    "Final FPS Approved": "June 15, 2025",
    "Final FSD Start": "June 18, 2025",
    "Tgl FPS disetujui": "June 15, 2025",
    "Tgl upload From Feedback ke PMA": "June 17, 2025",
    "Tanggal Canceled": null,
    "Tanggal Input Caldev": null,
    "Tanggal Input Timeline": null,
    "(FSD) Elapse Days": "5",
    "(FSD) Late Days": "0 (Tepat Waktu)",
    "(FSD) Status": "Done",
    "FSD SLA": "Achieved",
    "FSD SLA YEAR": 2025,
    "(Dev) Elapse Days": "14",
    "(Dev) Late Days": "0 (Tepat Waktu)",
    "(Dev) Status": "Done",
    "DEV SLA": "Achieved",
    "DEV SLA YEAR": 2025,
    "(SIT) Elapse Days": "4",
    "(SIT) Late Days": "0 (Tepat Waktu)",
    "(SIT) Status": "Done",
    "SIT SLA": "Achieved",
    "SIT SLA YEAR": 2025,
    "(UAT) Elapse Days": "5",
    "(UAT) Late Days": "0 (Tepat Waktu)",
    "(UAT) Status": "Done",
    "UAT SLA": "Achieved",
    "UAT SLA YEAR": 2025,
    "(Live) Realized in date": "November 08, 2025",
    "Live SLA": "Achieved",
    "LIVE SLA YEAR": 2025,
    "Reschedule UAT": 0,
    "Rata-rata Nilai Feedback User : ": null,
    "Rata-rata Nilai Feedback User New :": 0,
    "Bobot Project ": "Small"
  },
  {
    "Project Name": "Integrasi SLIK Checking Otomatis",
    "Ticket": "51860927",
    "Owner Name": "Rian Andriana",
    "Owner Div": "Risk Mgmt",
    "PIC Name": "Susilo Setio",
    "PIC Short Name": "Susilo",
    "Type Project": "Approval Digital",
    "Last Status": "Live On Monitoring",
    "Milestone": "CLOSED",
    "Status PMA": "CLOSED",
    "Prioritas Mgmt": "High",
    "Year": 2025,
    "Period": "Agu-25",
    "Kuartal": "Q3",
    "Durasi Project (IT)": "Agu–Des 2025",
    "Project diajukan": "Q3 2025",
    "Created time": "August 12, 2025 11:00 AM",
    "Last edited time": "June 17, 2026 5:00 PM",
    "Final FPS Approved": "August 18, 2025",
    "Final FSD Start": "August 22, 2025",
    "Tgl FPS disetujui": "August 18, 2025",
    "Tgl upload From Feedback ke PMA": "August 20, 2025",
    "Tanggal Canceled": null,
    "Tanggal Input Caldev": null,
    "Tanggal Input Timeline": null,
    "(FSD) Elapse Days": "12",
    "(FSD) Late Days": "0 (Tepat Waktu)",
    "(FSD) Status": "Done",
    "FSD SLA": "Achieved",
    "FSD SLA YEAR": 2025,
    "(Dev) Elapse Days": "42",
    "(Dev) Late Days": "8 (Telat Sedang 4-14 Hari)",
    "(Dev) Status": "Done",
    "DEV SLA": "Not Achieved",
    "DEV SLA YEAR": 2025,
    "(SIT) Elapse Days": "15",
    "(SIT) Late Days": "1 (Telat Ringan 1-3 Hari)",
    "(SIT) Status": "Done",
    "SIT SLA": "Not Achieved",
    "SIT SLA YEAR": 2025,
    "(UAT) Elapse Days": "10",
    "(UAT) Late Days": "0 (Tepat Waktu)",
    "(UAT) Status": "Done",
    "UAT SLA": "Achieved",
    "UAT SLA YEAR": 2025,
    "(Live) Realized in date": "December 15, 2025",
    "Live SLA": "Achieved",
    "LIVE SLA YEAR": 2025,
    "Reschedule UAT": 0,
    "Rata-rata Nilai Feedback User : ": null,
    "Rata-rata Nilai Feedback User New :": 0,
    "Bobot Project ": "Medium"
  },
  {
    "Project Name": "Sistem Manajemen Aset TI",
    "Ticket": "38194705",
    "Owner Name": "Taufik Hidayat",
    "Owner Div": "IT",
    "PIC Name": "Tri Susanto",
    "PIC Short Name": "Tri",
    "Type Project": "Internal IT",
    "Last Status": "Live On Monitoring",
    "Milestone": "CLOSED",
    "Status PMA": "CLOSED",
    "Prioritas Mgmt": "Low",
    "Year": 2025,
    "Period": "Sep-25",
    "Kuartal": "Q3",
    "Durasi Project (IT)": "Sep 2025–Jan 2026",
    "Project diajukan": "Q3 2025",
    "Created time": "September 02, 2025 9:00 AM",
    "Last edited time": "June 17, 2026 5:00 PM",
    "Final FPS Approved": "September 08, 2025",
    "Final FSD Start": "September 12, 2025",
    "Tgl FPS disetujui": "September 08, 2025",
    "Tgl upload From Feedback ke PMA": "September 10, 2025",
    "Tanggal Canceled": null,
    "Tanggal Input Caldev": null,
    "Tanggal Input Timeline": null,
    "(FSD) Elapse Days": "8",
    "(FSD) Late Days": "0 (Tepat Waktu)",
    "(FSD) Status": "Done",
    "FSD SLA": "Achieved",
    "FSD SLA YEAR": 2025,
    "(Dev) Elapse Days": "28",
    "(Dev) Late Days": "0 (Tepat Waktu)",
    "(Dev) Status": "Done",
    "DEV SLA": "Achieved",
    "DEV SLA YEAR": 2025,
    "(SIT) Elapse Days": "4",
    "(SIT) Late Days": "0 (Tepat Waktu)",
    "(SIT) Status": "Done",
    "SIT SLA": "Achieved",
    "SIT SLA YEAR": 2025,
    "(UAT) Elapse Days": "6",
    "(UAT) Late Days": "0 (Tepat Waktu)",
    "(UAT) Status": "Done",
    "UAT SLA": "Achieved",
    "UAT SLA YEAR": 2025,
    "(Live) Realized in date": "January 14, 2026",
    "Live SLA": "Achieved",
    "LIVE SLA YEAR": 2026,
    "Reschedule UAT": 0,
    "Rata-rata Nilai Feedback User : ": null,
    "Rata-rata Nilai Feedback User New :": 0,
    "Bobot Project ": "Medium"
  },
  {
    "Project Name": "Portal Vendor Management",
    "Ticket": "72053861",
    "Owner Name": "Umar Wirahadi",
    "Owner Div": "Ops",
    "PIC Name": "Vivin Alvina",
    "PIC Short Name": "Vivin",
    "Type Project": "Approval Digital",
    "Last Status": "Live On Monitoring",
    "Milestone": "CLOSED",
    "Status PMA": "CLOSED",
    "Prioritas Mgmt": "Medium",
    "Year": 2025,
    "Period": "Okt-25",
    "Kuartal": "Q4",
    "Durasi Project (IT)": "Okt 2025–Mar 2026",
    "Project diajukan": "Q4 2025",
    "Created time": "October 05, 2025 10:00 AM",
    "Last edited time": "June 17, 2026 5:00 PM",
    "Final FPS Approved": "October 10, 2025",
    "Final FSD Start": "October 12, 2025",
    "Tgl FPS disetujui": "October 10, 2025",
    "Tgl upload From Feedback ke PMA": "October 11, 2025",
    "Tanggal Canceled": null,
    "Tanggal Input Caldev": null,
    "Tanggal Input Timeline": null,
    "(FSD) Elapse Days": "11",
    "(FSD) Late Days": "0 (Tepat Waktu)",
    "(FSD) Status": "Done",
    "FSD SLA": "Achieved",
    "FSD SLA YEAR": 2025,
    "(Dev) Elapse Days": "31",
    "(Dev) Late Days": "0 (Tepat Waktu)",
    "(Dev) Status": "Done",
    "DEV SLA": "Achieved",
    "DEV SLA YEAR": 2025,
    "(SIT) Elapse Days": "5",
    "(SIT) Late Days": "0 (Tepat Waktu)",
    "(SIT) Status": "Done",
    "SIT SLA": "Achieved",
    "SIT SLA YEAR": 2025,
    "(UAT) Elapse Days": "8",
    "(UAT) Late Days": "0 (Tepat Waktu)",
    "(UAT) Status": "Done",
    "UAT SLA": "Achieved",
    "UAT SLA YEAR": 2025,
    "(Live) Realized in date": "March 18, 2026",
    "Live SLA": "Achieved",
    "LIVE SLA YEAR": 2026,
    "Reschedule UAT": 0,
    "Rata-rata Nilai Feedback User : ": null,
    "Rata-rata Nilai Feedback User New :": 0,
    "Bobot Project ": "Medium"
  },
  {
    "Project Name": "Sistem Antrian Digital Cabang",
    "Ticket": "46920178",
    "Owner Name": "Wawan Setiawan",
    "Owner Div": "ADV",
    "PIC Name": "ADV Team",
    "PIC Short Name": "ADV",
    "Type Project": "Project Utama",
    "Last Status": "Canceled",
    "Milestone": "CLOSED",
    "Status PMA": "CLOSED",
    "Prioritas Mgmt": "Medium",
    "Year": 2024,
    "Period": "Mei-24",
    "Kuartal": "Q2",
    "Durasi Project (IT)": "Mei–Nov 2024",
    "Project diajukan": "Q2 2024",
    "Created time": "May 10, 2024 11:00 AM",
    "Last edited time": "June 17, 2026 5:00 PM",
    "Final FPS Approved": "May 15, 2024",
    "Final FSD Start": "May 18, 2024",
    "Tgl FPS disetujui": "May 15, 2024",
    "Tgl upload From Feedback ke PMA": "May 20, 2024",
    "Tanggal Canceled": "November 12, 2024",
    "Tanggal Input Caldev": null,
    "Tanggal Input Timeline": null,
    "(FSD) Elapse Days": "12",
    "(FSD) Late Days": "0 (Tepat Waktu)",
    "(FSD) Status": "Done",
    "FSD SLA": "Achieved",
    "FSD SLA YEAR": 2024,
    "(Dev) Elapse Days": "21",
    "(Dev) Late Days": "0 (Tepat Waktu)",
    "(Dev) Status": "Done",
    "DEV SLA": "Achieved",
    "DEV SLA YEAR": 2024,
    "Reschedule UAT": 0,
    "Rata-rata Nilai Feedback User : ": null,
    "Rata-rata Nilai Feedback User New :": 0,
    "Bobot Project ": "Big"
  }
];
